image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean

tasks:
  - init: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh &&
          python3 -m pip install --user pipx &&
          python3 -m pipx ensurepath &&
          source ~/.profile &&
          pipx install mathlibtools
  
