[package]
name = "lean-mathgirls"
version = "0.1"
lean_version = "leanprover-community/lean:3.51.1"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "262a39ef44d4bde94328bf4da180042cc8d79c62"}